### ISSUE TITLE
Crashing tasks prevent the timer from repeating

### ISSUE THREAD

**Issue by ollien** [SchedEx/SchedEx#21] opened 2022-11-29 00:13 UTC
When evaluating this library, one thing I noticed is that if a repeating timer crashes, it is no longer rescheduled. This appears to be a logical consequence of some intended behavior; there's a test that asserts that caller processes are exit when their children crashes. 

https://github.com/SchedEx/SchedEx/blob/d68e3e5624aa9e05386b3f19aaefcb7d20a0c383/test/sched_ex_test.exs#L539-L552

Here's a unit test that demonstrates the problem
```elixir
describe "run_in" do
    # ...
    test "can repeat even after a crash", context do
      SchedEx.run_in(
        fn ->
          TestCallee.append(context.agent, 1)
          :erlang.error("oops")
        end,
        @sleep_duration,
        repeat: true
      )

      Process.sleep(round(2.5 * @sleep_duration))
      calls = TestCallee.clear(context.agent)
      assert length(calls) >= 2
      assert length(calls) <= 4
    end
    # ...
end
```

I can understand this behavior in the one-off case; it might be useful to be linked to the child you create. However, for repeating tasks, would lead to long-running tasks stopping after a single failure. This wouldn't be an issue if you supervised the timer, but is certainly a gotcha otherwise. I attempted a quick fix of this issue, but it violates the assertion set forth by the unit test linked above.

<details>
<summary>Attempted patch</summary>

```patch
diff --git a/lib/sched_ex/runner.ex b/lib/sched_ex/runner.ex
index 6bc3db9..0bc284a 100644
--- a/lib/sched_ex/runner.ex
+++ b/lib/sched_ex/runner.ex
@@ -40,6 +40,7 @@ defmodule SchedEx.Runner do
   def init({func, delay_definition, opts}) do
     Process.flag(:trap_exit, true)
     start_time = Keyword.get(opts, :start_time, DateTime.utc_now())
+    {:ok, task_supervisor_pid} = Task.Supervisor.start_link()
 
     case schedule_next(start_time, delay_definition, opts) do
       {%DateTime{} = next_time, quantized_next_time, timer_ref} ->
@@ -53,7 +54,8 @@ defmodule SchedEx.Runner do
            quantized_scheduled_at: quantized_next_time,
            timer_ref: timer_ref,
            stats: stats,
-           opts: opts
+           opts: opts,
+           task_supervisor: task_supervisor_pid
          }}
 
       {:error, _} ->
@@ -73,16 +75,19 @@ defmodule SchedEx.Runner do
           scheduled_at: this_time,
           quantized_scheduled_at: quantized_this_time,
           stats: stats,
-          opts: opts
+          opts: opts,
+          task_supervisor: task_supervisor
         } = state
       ) do
     start_time = DateTime.utc_now()
 
-    if is_function(func, 1) do
-      func.(this_time)
-    else
-      func.()
-    end
+    Task.Supervisor.start_child(task_supervisor, fn ->
+      if is_function(func, 1) do
+        func.(this_time)
+      else
+        func.()
+      end
+    end)
 
     end_time = DateTime.utc_now()
     stats = SchedEx.Stats.update(stats, this_time, quantized_this_time, start_time, end_time)
```

</details>

A fix for this might be considered a breaking change, so I held off. One fix might be to give a flag that teslls SchedEx to spawn the given function in a supervised task, defaulting to the current behavior.

**Comment by mtrudel** [comment] 2022-11-29 15:32
Thanks for the issue!

What you're seeing is very much by design. SchedEx quite intentionally doesn't provide supervision of any kind; if you want supervision you're expected to wire your SchedEx process into a supervision tree yourself (everything that SchedEx needs to run is present in its `start_link` arg, so standard OTP  supervisors will 'do the right thing' in this case). 

The design goal of a SchedEx process is to be a 'GenServer, but for time', not to provide task management. OTP does a great job of this already.

That all having been said, it is expected that SchedEx tasks get wired into supervision *somewhere* in basically all cases. Two of the most common patterns for this are outlined in the README. 

I'll close this issue as there's nothing more for the project to do here. If you have any other issues please feel free to bring them up!

**Closed as completed by mtrudel** 2022-11-29 15:32 UTC

**Comment by ollien** [comment] 2022-11-29 15:35
Totally makes sense. Thanks for clarifying!
