### ISSUE TITLE
No function clause matching in SchedEx.Runner.handle_info/2

### ISSUE THREAD

**Issue by bluzky** [SchedEx/SchedEx#12] opened 2019-09-17 06:19 UTC
Hi there,

I am getting this error message for some of my background task
```
** (FunctionClauseError) no function clause matching in SchedEx.Runner.handle_info/2
    (sched_ex) lib/sched_ex/runner.ex:67: SchedEx.Runner.handle_info({:job_terminated, #PID<0.6666.0>}, %{delay_definition: ~e[*/30 * * * * *], func: #Function<0.101805379/1 in SchedEx.mfa_to_fn/3>, opts: [repeat: true], quantized_scheduled_at: ~U[2019-09-17 06:30:00.000530Z], scheduled_at: ~U[2019-09-17 06:30:00Z], stats: %SchedEx.Stats{execution_time: %SchedEx.Stats.Value{avg: 42726081, count: 1, histogram: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], max: 42726081, min: 42726081}, quantization_error: %SchedEx.Stats.Value{avg: 22007, count: 1, histogram: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], max: 22007, min: 22007}, scheduling_delay: %SchedEx.Stats.Value{avg: 2275984154, count: 1, histogram: [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1], max: 2275984154, min: 2275984154}}})
    (stdlib) gen_server.erl:637: :gen_server.try_dispatch/4
    (stdlib) gen_server.erl:711: :gen_server.handle_msg/6
    (stdlib) proc_lib.erl:249: :proc_lib.init_p_do_apply/3
```

This error message only happen for some of my job, whereas others work well.
I looked at schedex code but I cannot find any helpful information to debug this.

Thank you,
Dung Nguyen

**Comment by mtrudel** [comment] 2019-09-17 13:13
Without having your project's source at hand, it would seem to me that this is a case of your application's job management logic 'leaking' into SchedEx. Remember that by design, SchedEx does not provide any supervision whatsoever over its runner processes, including the handling of messages (shutdown or otherwise) from elsewhere in your application. Other than the fact that there's a backing runner process that you can manage using conventional Supervisor semantics, the only sanctioned way to interact with a SchedEx process is via functions on the `SchedEx` module.

A tip-off here is that the symbol `:job_terminated` is not used anywhere internally within SchedEx, nor does a quick search yield any obvious Elixir libraries that use it either. My guess is that you're using such a symbol within your application to manage process lifecycles, and that that message is managing to make its way to a SchedEx runner task. 

Based on the above, I would take a look in your application or any libraries you may use (especially any which facilitate process management) and see if you can find any hints (I'd start by looking for the `:job_terminated` symbol to see who sends it, and to whom). 

In any case, this is not an issue with the SchedEx library and as such I'll be closing this issue. If subsequently you do end up finding a bona fide in SchedEx, please by all means do open another issue. In the meantime I hope SchedEx continues to be useful to you!

**Closed as completed by mtrudel** 2019-09-17 13:13 UTC
